### PR TITLE
[TRTLLM-14510][feat] serve: multi-process HTTP frontends on the classic IPC executor path

### PR DESCRIPTION
**Pull request by lancelly**
## Description

At high concurrency a `trtllm-serve` worker is **host-bound on its single serving process**: one asyncio event loop (one GIL) performs every request `json.loads`+pydantic validate and every SSE chunk write. Queuing on that loop — not GPU time — then dominates first-token latency (measured on DSv4 disagg GEN: `gen_preprocessing` p50 54ms@c512 → 109ms@c1024 → **1520ms@c2048**, an M/M/1-style blow-up while decode step time stayed flat).
This PR adds a prototype **multi-frontend mode** on the **default (classic IPC) executor path**: `num_serve_frontends: K` (llm-args knob / `--num_serve_frontends`, default 1 = off, max 64) runs K HTTP frontend processes against **one** executor.

### Design

- **Launcher/attach split** — the launcher (frontend 0) builds the LLM and launches workers as usual, then spawns K-1 children that re-exec the command line with `TLLM_EXECUTOR_ATTACH_INFO` set; their executor attaches via the new `GenerationExecutorFrontendProxy` (no MPI session, no worker launch, and shutdown never emits the worker's `None` engine-shutdown sentinel — the launcher alone owns the engine lifecycle).
- **Deterministic ipc endpoints**, pre-generated by the launcher (`TLLM_MULTI_FRONTEND_IPC_DIR`/`_HMAC`): the rank0 worker **binds** the request ingress (PULL) so every frontend PUSH-connects; each frontend binds its own result lane (PULL) that the worker (non-postproc) or every postprocess worker (one PUSH pipe per frontend) sends to.
- **client-id namespacing** — the top 16 bits of the uint64 client id carry the frontend id; responses route by `client_id>>48`. Responses without a usable client id (e.g. attention-DP dummy requests carry `client_id=None`) route to the launcher, preserving today's silent-discard semantics. Frontend 0 / feature-off keeps ids bit-identical to today.
- **SO_REUSEPORT** — all frontends bind the public port; the kernel load-balances accepted connections across independent processes (and GILs). Clients and the disagg orchestrator still see one URL.

image

### Scope / limitations (prototype)

- Classic IPC executor path only; `orchestrator_type: rpc`/`ray` are rejected with a clear error.
- Configured via the `num_serve_frontends` llm-args knob (prototype status), capped at 64.
- `/metrics`, `/perf_metrics`, `/health` are served per-frontend (SO_REUSEPORT samples one frontend per request); cross-frontend aggregation is follow-up work.
- `enable_resource_governor` is rejected in multi-frontend mode (the governor signal only reaches the launcher).

## Summary by CodeRabbit

* **New Features**
  * Added support for running multiple HTTP serving frontends per executor.
  * Added the `num_serve_frontends` configuration option, supporting 1–64 frontends.
  * Improved request and response routing so each frontend receives its corresponding results.
  * Added frontend attachment support for connecting to an existing serving process.
* **Bug Fixes**
  * Prevented attached frontends from unnecessarily starting duplicate worker sessions.
* **Tests**
  * Added coverage for multi-frontend routing, client isolation, response delivery, and shutdown behavior.

### CODE REVIEW

File: tensorrt_llm/commands/serve.py [hunk 1]
```diff
@@ -358,6 +363,118 @@ def _diagnose_port_in_use(port: int) -> str:
...
+    executor = getattr(llm, "_executor", None)
+    if not isinstance(executor, GenerationExecutorProxy) or (
+            attach_info := executor.multi_frontend_attach_info()) is None:
+        raise ValueError(
+            "num_serve_frontends > 1 requires the classic IPC executor "
+            f"proxy in multi-frontend mode, got {type(executor).__name__}")
+    # mkstemp creates the file 0600: it carries the executor HMAC keys.
+    fd, attach_info_path = tempfile.mkstemp(prefix="trtllm_frontend_",
+                                            suffix=".json")
+    with os.fdopen(fd, "w") as f:
```
Comment (reasonsolo) [inline tensorrt_llm/commands/serve.py]: With less hassle we can use the serialized json as  value of TLLM_EXECUTOR_ATTACH_INFO, no need for creating and deleting an extra file.

File: tensorrt_llm/commands/serve.py [hunk 2]
```diff
@@ -358,6 +363,118 @@ def _diagnose_port_in_use(port: int) -> str:
     return "; ".join(details)
 
 
+class MultiFrontendMode(NamedTuple):
```
Comment (reasonsolo) [inline tensorrt_llm/commands/serve.py:366]: MultiFrontendMode and _init_multi_frontend_mode look verbose, can you ask agent to simplify this?

File: tensorrt_llm/executor/postproc_worker.py [hunk 3]
```diff
@@ -86,7 +86,8 @@ class Output(NamedTuple):
     def __init__(
         self,
         pull_pipe_addr: tuple[str, Optional[bytes]],
-        push_pipe_addr: tuple[str, Optional[bytes]],
+        push_pipe_addr: Union[tuple[str, Optional[bytes]],
+                              List[tuple[str, Optional[bytes]]]],
```
Comment (reasonsolo) [inline tensorrt_llm/executor/postproc_worker.py]: Backaward compatibility is not necessary. `Union[tuple, List[tuple]] ` -> `List[tuple]` through the call stack will be cleaner.

File: tensorrt_llm/executor/utils.py [hunk 4]
```diff
@@ -229,6 +229,62 @@ class WorkerCommIpcAddrs(NamedTuple):
...
+    # these lanes; result_queue_addr then aliases lane 0 (the launcher).
+    frontend_result_queue_addrs: Optional[list[tuple[str,
+                                                     Optional[bytes]]]] = None
+
+
+# Multi-frontend client_id namespacing: the top bits of the uint64 client id
+# carry the frontend id, the low FRONTEND_ID_SHIFT bits carry the per-frontend
+# request counter. Frontend id 0 keeps client ids bit-identical to the legacy
+# single-frontend scheme.
+FRONTEND_ID_SHIFT = 48
```
Comment (reasonsolo) [inline tensorrt_llm/executor/utils.py]: > Frontend id 0 keeps client ids bit-identical

This may lead to bug: long running services will generate wrong frontend id from frontend 0. Lane 0 should also generate client id by the same rule, unless multiple frontend is disabled. Also define a max frontend id width, say, 6 or 8, then derive the max frontend number/SHIFT/MASK from it. And an ID is better to be positive, to make the IDs monotonic. The order of sequence id part and frontend id part  is debatable, it depends on how you prefer to order by sequence/timing or frontend primarily.

File: tensorrt_llm/commands/serve.py (hunk 1 above)
Comment (lancelly) [reply tensorrt_llm/commands/serve.py]: Done.

File: tensorrt_llm/commands/serve.py (hunk 2 above)
Comment (lancelly) [reply tensorrt_llm/commands/serve.py:366]: Done.

File: tensorrt_llm/executor/postproc_worker.py (hunk 3 above)
Comment (lancelly) [reply tensorrt_llm/executor/postproc_worker.py]: Done.

**Review by reasonsolo — APPROVED** [review]

File: tests/unittest/executor/test_multi_frontend_routing.py [hunk 5]
```diff
@@ -0,0 +1,249 @@
...
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+"""CPU-only tests for classic-path multi-frontend serving.
+
+Multi-frontend serving (num_serve_frontends) on the classic IPC
+executor path. Covers client-id namespacing, worker-side response-lane routing, and the
+attached-frontend proxy lifecycle over real ipc:// sockets.
```
Comment (QiJune) [inline tests/unittest/executor/test_multi_frontend_routing.py:19]: We need to re-enable the `unittest/executor` directory in CI first. Currently, new tests under this directory are not automatically collected, so regressions like the missing _engine_dead initialization can slip through unnoticed.

File: tensorrt_llm/executor/proxy.py [hunk 6]
```diff
@@ -911,3 +1007,99 @@ def __enter__(self):
...
+        if not 0 < frontend_id < num_lanes:
+            raise ValueError(
+                f"frontend_id {frontend_id} out of range: attached frontends "
+                f"use ids 1..{num_lanes - 1} (id 0 is the launcher)")
+        postproc_worker_config = postproc_worker_config or PostprocWorkerConfig(
+        )
+        # Deliberately skip GenerationExecutorProxy.__init__: it creates an
+        # MPI session, launches workers, and registers the pre_shutdown
+        # atexit hook that emits the engine shutdown sentinel.
+        GenerationExecutor.__init__(
```
Comment (QiJune) [inline tensorrt_llm/executor/proxy.py:1046]: GenerationExecutorFrontendProxy skips GenerationExecutorProxy.__init__, but still inherits methods that require _engine_dead, _worker_process_monitor, and model_world_size. As a result, the first submit() raises AttributeError, /health fails, and collective-RPC-backed routes may also fail. Please explicitly define the attached-frontend state and health contract instead of inheriting owner-only assumptions, and add submit/health regression tests.

File: tensorrt_llm/commands/serve.py [hunk 7]
```diff
@@ -358,6 +361,89 @@ def _diagnose_port_in_use(port: int) -> str:
...
+
+    children = []
+    for frontend_id in range(1, num_frontends):
+        # Strip MPI/SLURM identity vars: an inherited rank identity would
+        # make the child's mpi4py try to (re-)join the launcher's job.
+        env, _ = split_mpi_env()
+        env["TLLM_EXECUTOR_ATTACH_INFO"] = attach_env
+        env["TLLM_EXECUTOR_FRONTEND_ID"] = str(frontend_id)
+        env["TLLM_DISABLE_MPI"] = "1"
+        child = subprocess.Popen([sys.executable] + sys.argv,
```
Comment (QiJune) [inline tensorrt_llm/commands/serve.py]: Could we add a readiness handshake and child-liveness monitoring here? A successful Popen only means that the process was created; an attached frontend may still fail during executor attachment, model initialization, or public-port setup while the launcher continues serving. In that case num_serve_frontends=K silently runs with fewer than K frontends and can produce misleading benchmark results. Startup should require a READY acknowledgement from every child and fail the group if any required frontend exits.

File: tensorrt_llm/commands/serve.py [hunk 8]
```diff
@@ -427,7 +526,11 @@ def launch_server(
         if os.getenv("TRTLLM_SERVER_DISABLE_GC", "0") == "1":
             gc.disable()
 
-        uvloop.run(server(host, port, sockets=[s]))
+        try:
```
Comment (QiJune) [inline tensorrt_llm/commands/serve.py:591]: The cleanup scope starts too late. The attached frontends have already been spawned before OpenAIServer construction and middleware registration, so an exception in either path leaves the child processes running. A partial failure inside _spawn_attached_frontends can also leak the children that were started earlier in the loop. Please make child startup exception-safe and move the cleanup boundary so it covers spawning, server construction, middleware registration, and runtime.

File: tensorrt_llm/commands/serve.py [hunk 9]
```diff
@@ -372,17 +458,25 @@ def launch_server(
...
                                    socket.SOCK_STREAM)
     address_family = socket.AF_INET6 if all(
         [info[0] == socket.AF_INET6 for info in addr_info]) else socket.AF_INET
     with socket.socket(address_family, socket.SOCK_STREAM) as s:
         # If disagg cluster config is provided and port is not specified, try to find a free port, otherwise try to bind to the specified port
         assert port > 0 or disagg_cluster_config is not None, "Port must be specified if disagg cluster config is not provided"
+        if multi_frontend.is_launcher or multi_frontend.is_attached_frontend:
+            # Every frontend process binds its own listening socket on the
+            # same port; the kernel load-balances accepts across them.
+            s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
```
Comment (QiJune) [inline tensorrt_llm/commands/serve.py:559]: Stateful Responses are enabled by default today: ResponsesRequest.store defaults to true, and each frontend owns a separate in-memory ConversationHistoryStore. A follow-up connection that lands on a sibling frontend may therefore fail to resolve previous_response_id, retrieve, or delete the response. Please either disable/reject stateful Responses in multi-frontend mode or provide shared/owner-routed storage.

File: tests/unittest/executor/test_multi_frontend_routing.py (hunk 5 above)
Comment (lancelly) [reply tests/unittest/executor/test_multi_frontend_routing.py:19]: Done.

File: tensorrt_llm/executor/proxy.py (hunk 6 above)
Comment (lancelly) [reply tensorrt_llm/executor/proxy.py:1046]: Fixed. Thanks

**Review by BowenFu — APPROVED** [review]
LGTM on the regression lens — multi-process frontends are opt-in via num_serve_frontends (default 1 = off); the single-process path is preserved (postproc _batched_put len==1 fast path, request-queue zmq.PAIR when off, client-ids identical for frontend 0), and the FrontendProxy __init__ that skips parent init only affects the attached multi-frontend proxy. Two open items to resolve before merge (not blocking my regression review): the CodeRabbit-flagged FrontendProxy.__init__ leaving _engine_dead/_worker_process_monitor unset, and QiJune's in-flight review.

**Review by fredricz-20070104 — APPROVED** [review]
Approved.

File: tensorrt_llm/commands/serve.py [hunk 10]
```diff
@@ -358,6 +363,156 @@ def _diagnose_port_in_use(port: int) -> str:
...
+    while pending:
+        remaining = deadline - time.monotonic()
+        if remaining <= 0:
+            raise RuntimeError(
+                f"{len(pending)} attached frontend(s) not ready within "
+                f"{timeout:.0f}s (TLLM_FRONTEND_READY_TIMEOUT)")
+        readable, _, _ = select.select(list(pending), [], [],
+                                       min(remaining, 1.0))
+        for fd in readable:
+            child = pending.pop(fd)
```
Comment (QiJune) [inline tensorrt_llm/commands/serve.py:477]: Thanks for adding the READY handshake. One non-blocking follow-up: once a child is removed from pending here, it is no longer monitored. If it exits after signaling READY—while other frontends are still starting or later at runtime—the launcher can silently continue with fewer than num_serve_frontends processes. Could you please follow up with continuous child-liveness monitoring, or create atracking issue if it is better handled separately? I won’t block this PR on it.

**Review by QiJune — APPROVED** [review]
LGTM

File: tensorrt_llm/commands/serve.py (hunk 10 above)
Comment (lancelly) [reply tensorrt_llm/commands/serve.py:477]: Thanks. I noticed this, too. But I'm not sure whether monitoring would add additional overhead. I created a [jira](https://jirasw.nvidia.com/browse/TRTLLM-14516) that tracks this.

**Comment by longcheng-nv** [comment]
Heads-up: this PR appears to have introduced a semantic conflict with `tests/unittest/executor/test_proxy_fast_death.py` that is failing on current main (unwaived).

- This PR added `self._multi_frontend_ipc_dir` (assigned in `__init__`, proxy.py:174) and `shutdown()` now always calls `_cleanup_multi_frontend_ipc_dir()` — including the `workers_started=False` early-return path.
- `test_proxy_fast_death.py` constructs proxies via `GenerationExecutorProxy.__new__` without running `__init__` (`_bare_proxy()`), so every `proxy.shutdown()` — and the `__del__` GC path of every such mock — raises:

```text
AttributeError: 'GenerationExecutorProxy' object has no attribute '_multi_frontend_ipc_dir'
proxy.py:797 shutdown -> proxy.py:739 _cleanup_multi_frontend_ipc_dir
```

- Observed failing in PR CI runs L0 #49263 and #49333 (A10 stage, 3 tests, persists through rerun; reproduced locally on main tip).
- Suggested fix (same pattern as #16630, which seeded other bypassed attrs in this file): add `proxy._multi_frontend_ipc_dir = None` to `_bare_proxy()`; alternatively make `_cleanup_multi_frontend_ipc_dir` use `getattr(self, '_multi_frontend_ipc_dir', None)` for robustness.

I am temporarily carrying the one-line test fix on PR #16457 to unblock its CI; happy to drop it once a proper fix lands.
