### PR TITLE
[https://nvbugs/6513132][fix] DSA: rebuild token-to-request map inside the MTP draft loop

### PR DESCRIPTION
**Pull request by zheyuf**
## The problem (for both GLM5.2 and DSV3.2):
**(1) MTP acceptance rate has regression when batch size is large**: https://nvbugspro.nvidia.com/bug/6513093 
**(2) There is a gap of AL between TRTLLM and vLLM**:https://nvbugspro.nvidia.com/bug/6513132

The root cause is the stale token→request map in DSA.py. req_idx_per_token is initially built from the target forward layout, where each request contributes max_draft_len + 1 tokens. During the one-model draft loop, the layout changes to one token per request, but on_update_kv_lens() recomputes seq_starts while reusing the old map (the map is stale). This corrupts sparse-index reads through the wrong request’s block table and also corrupts Indexer-K writes into the wrong request’s KV pages.

## Fix
Rebuild the map from the current `seq_lens` with a device-side `searchsorted`. 

Deepseek v4 doesn't have such acceptance rate regression as `DeepseekV4TrtllmAttentionMetadata` already rebuilt this map in its own `on_update_kv_lens()` override, so this is a port of existing behaviour to the base class, not new logic.

## NVBugs fixed by this PR
https://nvbugspro.nvidia.com/bug/6513132, https://nvbugspro.nvidia.com/bug/6513093 

---

## Results — before / after

All A/B pairs are the same image and harness, differing **only** by this change.
### GLM-5.2 NVFP4 — offline `trtllm-bench`, 1×GB200 tp4/ep4 + ADP, MTP k=7, greedy

| concurrency | per-rank batch | AL before | AL after | Δ |
|---:|---:|---:|---:|---:|
| 8 | 2 | 3.500 | **3.943** | +12.6% |
| 64 | 16 | 2.789 | **3.909** | +40.2% |

### DeepSeek-V3.2 NVFP4 — the second affected model, same harness, k=7 greedy

| concurrency | per-rank batch | AL before | AL after | Δ |
|---:|---:|---:|---:|---:|
| 8 | 2 | 2.5397 | **2.6379** | +3.9% |
| 64 | 16 | 2.3994 | **2.6587** | +10.8% |
| 128 | 32 | 2.3795 | **2.6769** | +12.5% |

Slope c8 → c128: **−6.3% → +1.5%** (flat). Same qualitative signature on an independent model.

The above proves that **(1) MTP acceptance rate has regression when batch size is large** is fixed.

### GLM-5.2 — depth sweep at c8, against a same-session vLLM reference

| k | before | after | vLLM | gap before | gap after |
|---:|---:|---:|---:|---:|---:|
| 1 | 1.8429 | 1.8504 | 1.849 | 0.006 | −0.001 |
| 4 | 3.0132 | 3.2547 | 3.362 | 0.349 | 0.107 |
| 7 | 3.3178 | 3.7032 | 3.789 | 0.471 | 0.086 |

The above proves that **(2)There is a gap of AL between TRTLLM and vLLM**  is fixed.

### GPQA-Diamond, 198 questions — accuracy is unaffected, as the mechanism requires

GB300 1p1d disagg, c128, MTP k=7, T=1 + rejection sampling, `max_seq_len 400000`:

| | before | after |
|---|---:|---:|
| symbolic_correct | 85.354% | 85.859% |
| no_answer | 5.556% | 3.030% |
| avg generated tokens | 57,171 | 55,662 |
| **generation wall-clock** | **5,117 s** | **3,322 s** (−35%) |

---

## What models get fixed

| architecture | models | metadata class | affected? |
|---|---|---|---|
| `DeepseekV32ForCausalLM` | DeepSeek-V3.2 / V3.2-Exp | `DSAtrtllmAttentionMetadata` (patched) | **yes**, when `max_draft_len ≥ 2` |
| `GlmMoeDsaForCausalLM` | GLM-5, GLM-5.2 | same (patched) | **yes**, same condition |

## Dev Engineer Review

- Added `build_req_idx_per_token()` in `dsa.py`.
- Rebuilds the token-to-request map from current sequence lengths with device-side `torch.searchsorted`.
- Supports zero-length requests and CUDA graph execution.
- Updates `on_update_kv_lens()` to refresh the map before slot mapping.
- Updates DeepSeek-V4 position computation to use the refreshed buffer.
- No configuration or test-list changes.
- The change prevents stale request mappings during one-model MTP draft loops and avoids incorrect sparse-index and KV-page accesses.

## QA Engineer Review

- Added tests for device-side request-index construction across CPU and CUDA layouts.
- Added coverage for zero-length requests.
- Added a CUDA regression test for rebuilding stale request mappings after draft-loop sequence lengths change.
- No matching entries were found in `tests/integration/test_lists`, `test-db`, or `qa`.
- Verdict: needs follow-up.

### CODE REVIEW

**Comment by zheyuf** [comment]
Hi @yunruis @pengbowang-nv, could you help review this PR to unblock GLM5.2 Agentperf submission? CI has passed. Thanks!

**Comment by yunruis** [comment]
Could I understand it is what your PR do? 

```
start_positions = kv_lens - seq_lens = [100-1, 200-1, 300-1] = [99, 199, 299]
```

Before:

```
req_indices = req_idx_per_token[:3]
#           = [0, 0, 0]   â è¯»å3ä¸ªï¼å¨æ¯req0ï¼åºè¯¥æ¯[0,1,2]

seq_starts = cumsum([1,1,1]) - [1,1,1]
           = [1,2,3] - [1,1,1]
           = [0, 1, 2]

token_offsets = arange(3) - seq_starts[req_indices]
              = [0,1,2]   - seq_starts[[0,0,0]]
              = [0,1,2]   - [0,0,0]
              = [0, 1, 2]

global_positions = start_positions[req_indices] + token_offsets
                 = start_positions[[0,0,0]]      + [0,1,2]
                 = [99, 99, 99]                  + [0,1,2]
                 = [99, 100, 101]   # error !
```

After repair: 

```
cu_seq_lens = cumsum([1,1,1]) = [1, 2, 3]
token_idx   = [0, 1, 2]

# searchsorted(sorted_seq, val, right=True) 

req_idx_per_token[:3] = searchsorted([1,2,3], [0,1,2], right=Tru
                      = [0, 1, 2]   â æ­£ç¡®ï¼

req_indices = [0, 1, 2]

seq_starts = cumsum([1,1,1]) - [1,1,1]
           = [1,2,3] - [1,1,1]
           = [0, 1, 2]

token_offsets = arange(3) - seq_starts[req_indices]
              = [0,1,2]   - seq_starts[[0,1,2]]
              = [0,1,2]   - [0,1,2]
              = [0, 0, 0]    
global_positions = start_positions[req_indices] + token_offsets
                 = start_positions[[0,1,2]]      + [0,0,0]
                 = [99, 199, 299]                + [0,0,0]
                 = [99, 199, 299]    # right !
```

**Comment by zheyuf** [comment]
@yunruis Yes, exactly — your walkthrough is precisely what the PR fixes.

**Review by BowenFu — APPROVED** [review]
Checked the regression axis: `searchsorted(cumsum(seq_lens), arange(num_tokens), right=True)` is exactly `prepare_for_indices_conversion()`'s `repeat_interleave` (dsa.py:1694) whenever `seq_lens` is unchanged — including zero-length rows — so the non-MTP DSA path is unaffected. DeepSeek-V4 is bit-identical: its override calls `super().on_update_kv_lens()` and then rewrites the same buffer with the identical searchsorted in `_compute_token_positions()` (deepseek_v4.py:913-918).

Not blocking on these, but worth a follow-up: the map is now built three ways (dsa.py:1694 CPU, dsa.py:841 device, deepseek_v4.py:913 device) — V4's copy is now redundant work every step and a shared helper would stop them drifting. And there is no unit test pinning the rebuilt map against the draft-loop layout; the benchmark deltas are convincing but they will not catch a regression here.

**Comment by zheyuf** [comment]
@BowenFu thanks a lot for the review. I agree that it worth a follow-up and let me do the fix in this PR.

**Comment by zhaoyangwang-nvidia** [comment]
Hi @zheyuf — your PR also covers a fix for one of our NVBugs (https://nvbugs/6463964): MTP acceptance length on GLM-5.2 (DSA + one-model MTP) degrades as batch size grows, which turned out to be the same stale token→request map you're fixing here.

I verified your PR resolves it locally — GLM-5.2-NVFP4, TP=4, 80 MT-bench prompts, greedy, max_draft_len=4: batch=8 acceptance length goes from 3.283 → 3.739, matching batch=1 (3.734). Same with CUDA graphs on.

I had a duplicate fix open (#17240) and have closed it in favor of yours, and assigned 6463964 to you as well since this PR is what will resolve it.

**Comment by zheyuf** [comment]
Thanks @zhaoyangwang-nvidia, my PR is exactly targeting the same problem that MTP acceptance length on GLM-5.2 degrades as batch size grows: here are my two NVBugs https://nvbugspro.nvidia.com/bug/6513132, https://nvbugspro.nvidia.com/bug/6513093.

Sorry that I was unaware that you were also working on this problem, otherwise I should have contacted you to prevent our duplicated effort. Seems like our NVBugs are pretty duplicated :joy:

**Comment by zheyuf** [comment]
@BowenFu I have added the shared helper and the unit test pinning the rebuilt map against the draft-loop layout according to your comments. Thanks.

**Comment by zheyuf** [comment]
Still need a stamp from @NVIDIA/trt-llm-torch-attention-devs to merge this PR. I have added the shared helper and the unit test pinning the rebuilt map against the draft-loop layout according to BowenFu's comments. CI passed again. Kindly @yunruis @pengbowang-nv for review. :pray:

**Comment by longcheng-nv** [comment]
Heads-up: the unit test added here appears to break premerge CI on current main (merge skew with the `in_mtp_draft_loop` state from #15806).

**Failure** (seen in PR #16666's premerge, pipeline `L0_MergeRequest_PR` #52320, reproduced identically on both DGX_B200 and B300 `unittest/_torch/attention` buckets; not waived in `waives.txt`):

```
unittest/_torch/attention/sparse/dsa/test_req_idx_per_token.py::test_on_update_kv_lens_rebuilds_stale_map
tensorrt_llm/_torch/attention_backend/sparse/dsa.py:845: in on_update_kv_lens
    if not self.in_mtp_draft_loop:
E   AttributeError: 'DSAtrtllmAttentionMetadata' object has no attribute 'in_mtp_draft_loop'. Did you mean: 'set_in_mtp_draft_loop'?
```

**Mechanism**: `test_on_update_kv_lens_rebuilds_stale_map` constructs the metadata via `object.__new__(DSAtrtllmAttentionMetadata)` and stubs collaborators by hand, but does not stub `in_mtp_draft_loop`. On current main, `on_update_kv_lens()` reads `self.in_mtp_draft_loop` (the shared-top-k clearing introduced with the MTP indexer top-k sharing feature), so the test raises before reaching the map-rebuild assertion. Each PR was green on its own base; the combination on main is what fails.

**Suggested fix** (either works):
- in the test, add `md.in_mtp_draft_loop = False` next to the other stubs, or
- make the read defensive: `if not getattr(self, 'in_mtp_draft_loop', False):` in `on_update_kv_lens`.

Happy to send a one-line PR for the test-side fix if that helps.

**Comment by zheyuf** [comment]
Thanks @longcheng-nv, seems like the test side fix is merged in this PR: https://github.com/NVIDIA/TensorRT-LLM/pull/17416 and the pre-merge CI should be unblocked now.
