### ISSUE TITLE
Failure to run nvfp4 GLM 4.5

### ISSUE THREAD

**Issue by laikhtewari** [NVIDIA/TensorRT-LLM#6569]
### System Info

B200

### Who can help?

@juney-nvidia @Tracin 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Using https://github.com/deepinfra/TensorRT-LLM/tree/glm-jul28 (forked from upstream main 7/28), works with GLM-4.5-Air BF16 version correctly

Steps:
1. Quantize FP4 GLM-4.5-Air (in modelopt docker)
```
huggingface-cli download zai-org/GLM-4.5-Air
HF_PATH=./zai-org/GLM-4.5-Air
cd examples/llm_ptq
scripts/huggingface_example.sh --model $HF_PATH --quant nvfp4 --export_fmt hf
```
2. Run trtllm-serve (in tensorrt_llm docker)
```
export NCCL_NVLS_ENABLE=0; trtllm-serve /data/weights/vllm-zai-org--GLM-4.5-Air-FP4 --tp_size=8 --host=0.0.0.0 --port=8000 --backend=pytorch --max_num_tokens=4000 --max_seq_len 3000 --ep_size=8 --pp_size=1 --max_batch_size=1 --extra_llm_api_options extra-llm-api-config.yml
```

If I try to do the same steps with the GLM-4.5 none Air version, it hangs in one of the transformer layers. Even with BF16 weights. (Note, I also disabled the w1_weight_scale_2 != w3_weight_scale_2 check)

extra_llm_api_config.yml
```
enable_attention_dp: false
max_batch_size: 1
max_num_tokens: 4000
max_seq_len: 3000
kv_cache_config:
  free_gpu_memory_fraction: 0.8
enable_chunked_prefill: true
print_iter_log: true
disable_overlap_scheduler: true
```

### Expected behavior

NVFP4 ckpt converted from model opt should work

### actual behavior

``` 
 File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/models/modeling_deepseekv3.py", line 1247, in load_weights
    _load_weights_impl(self, weights, params_map={
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/models/modeling_utils.py", line 711, in _load_weights_impl
    module.load_weights(weights=[module_weights])
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/modules/fused_moe/fused_moe_cutlass.py", line 437, in load_weights
    self.quant_method.load_weights(self, weights, self.weight_loading_mode)
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/modules/fused_moe/quantization.py", line 128, in load_weights
    self.load_quant_scales(module, weights)
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/modules/fused_moe/quantization.py", line 989, in load_quant_scales
    self.load_all_fp4_weight_scales_and_alphas(
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/modules/fused_moe/quantization.py", line 947, in load_all_fp4_weight_scales_and_alphas
    self.load_expert_fc31_alpha_nvfp4(w1_weight_scale_2,
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/modules/fused_moe/quantization.py", line 897, in load_expert_fc31_alpha_nvfp4
    assert torch.allclose(
           ^^^^^^^^^^^^^^^
AssertionError: w1_weight_scale_2 != w3_weight_scale_2
```

### additional notes

None

**Comment by Shang-Pin** [comment]
Some additional notes
1. Both containers need to update to latest transformers package
2. The GLM-4.5-Air-FP4 will crash with the following error if we skip the w1_weight_scale_2 != w3_weight_scale_2 check.
```
 File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/modules/gated_mlp.py", line 132, in forward
    output = self.down_proj(h2,
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/modules/linear.py", line 906, in forward
    output = self.apply_linear(input, bias, lora_params, layer_idx)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/modules/linear.py", line 867, in apply_linear
    output = self.quant_method.apply(self, input, bias)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/modules/linear.py", line 520, in apply
    output = torch.ops.trtllm.nvfp4_gemm(act_fp4, module.weight, act_sf,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/_ops.py", line 1158, in __call__
    return self._op(*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/_library/custom_ops.py", line 344, in backend_impl
    result = self._backend_fns[device_type](*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/_compile.py", line 51, in inner
    return disable_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py", line 850, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/_library/custom_ops.py", line 377, in wrapped_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/custom_ops/torch_custom_ops.py", line 321, in nvfp4_gemm
    return nvfp4_gemm_runner(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/autotuner.py", line 161, in __call__
    return self.forward(inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/_torch/custom_ops/torch_custom_ops.py", line 286, in forward
    return self.fp4_gemm_runner.run_gemm(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected k to be divisible by 32, but got mat1 shape: (3039x1368), k: 2736.
```

**Comment by jhaotingc** [comment]
Adding to this thread: same `AssertionError: w1_weight_scale_2 != w3_weight_scale_2` error can be found after quantizing [Qwen/Qwen3-235B-A22B-Thinking-2507](https://huggingface.co/Qwen/Qwen3-235B-A22B-Thinking-2507). 
Investigating.

**Comment by dmtri35** [comment]
@jhaotingc do you know what previous modelopt version doesnt have this issue?

**Comment by BitPhinix** [comment]
Also running into this - even with the fix it just frezzes

**Comment by voipmonitor** [comment]
> ### System Info
> B200
> 
> ### Who can help?
> [@juney-nvidia](https://github.com/juney-nvidia) [@Tracin](https://github.com/Tracin)
> 
> ### Information
> * [ ]  The official example scripts[ ]  My own modified scripts
> 
> ### Tasks
> * [ ]  An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)[ ]  My own task or dataset (give details below)
> 
> ### Reproduction
> Using https://github.com/deepinfra/TensorRT-LLM/tree/glm-jul28 (forked from upstream main 7/28), works with GLM-4.5-Air BF16 version correctly

Hello, would love to help with this but - how did you built this docker? Still with  make -C docker release_build CUDA_ARCHS="120-real" - or did you do any adjustments? Because I'm running this forked glm-junl28 

trtllm-serve /mnt/GLM-4.5-Air --tp_size=4 --host=0.0.0.0 --port=8000 --backend=pytorch --max_num_tokens=4000 --max_seq_len 3000 --ep_size=1 --pp_size=1 --max_batch_size=1 --extra_llm_api_options /app/extra-llm-api-config.yml 

and I'm getting: 

 Failed to initialize executor on rank 0: AttributeError: type object 'CompiledKernel' has no attribute 'launch_enter_hook'

**Comment by Shang-Pin** [comment]
@voipmonitor I just re-tested it agin. No other changes. Here are the exact steps.
1. Clone the repo https://github.com/deepinfra/TensorRT-LLM/tree/glm-jul28 
2. make -C docker release_build CUDA_ARCHS="90-real;100-real;120-real"
3. start docker (on B200, didn't test other GPUs)
4. pip install --upgrade transformers
5. The exact extra-llm-api-config.yml above
6. export NCCL_NVLS_ENABLE=0; trtllm-serve /data/weights/vllm-zai-org--GLM-4.5-Air-BF16 --tp_size=4 --host=0.0.0.0 --port=8000 --backend=pytorch --max_num_tokens=4000 --max_seq_len 3000 --ep_size=4 --pp_size=1 --max_batch_size=1 --extra_llm_api_options extra_llm_api_config.yml

**Comment by voipmonitor** [comment]
I have done exactly what you did but I'm getting errors

```
  File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/async_compile.py", line 341, in get_result
    kernel.precompile(
  File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_heuristics.py", line 323, in precompile
    self._make_launchers()
  File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_heuristics.py", line 480, in _make_launchers
    launchers.append(result.make_launcher())
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_heuristics.py", line 1422, in make_launcher
    "launch_enter_hook": binary.__class__.launch_enter_hook,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch._inductor.exc.InductorError: AttributeError: type object 'CompiledKernel' has no attribute 'launch_enter_hook'
```
  
 vllm-zai-org--GLM-4.5-Air-BF16 - is this https://huggingface.co/zai-org/GLM-4.5-Air ?

**Comment by voipmonitor** [comment]
> [@voipmonitor](https://github.com/voipmonitor) I just re-tested it agin. No other changes. Here are the exact steps.


I have done exactly what you did but I'm getting errors

  File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/async_compile.py", line 341, in get_result
    kernel.precompile(
  File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_heuristics.py", line 323, in precompile
    self._make_launchers()
  File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_heuristics.py", line 480, in _make_launchers
    launchers.append(result.make_launcher())
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_heuristics.py", line 1422, in make_launcher
    "launch_enter_hook": binary.__class__.launch_enter_hook,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch._inductor.exc.InductorError: AttributeError: type object 'CompiledKernel' has no attribute 'launch_enter_hook'
vllm-zai-org--GLM-4.5-Air-BF16 - is this https://huggingface.co/zai-org/GLM-4.5-Air ?
