### PR TITLE
[TRTLLM-12154][test] Add Qwen3-32B FP8 disagg stress test

### PR DESCRIPTION
**Pull request by brnguyen2**
## Summary

Adds Qwen3-32B FP8 disaggregated serving coverage for the Eagle3 path on 8 GPUs.

The new disagg config uses:
- target model: `Qwen3/Qwen3-32B-FP8`
- Eagle3 draft model: `Zhi-Create-Qwen3-32B-Eagle3`, resolved relative to `llm_models_root()`
- 4 context workers with TP1 and 1 generation worker with TP4
- FP8 KV cache, chunked prefill, block/partial reuse, and DEFAULT cache transceiver
- top-level `speculative_config` so context and generation workers agree on the cache-state handshake

The disagg harness now resolves relative `model` and `speculative_config.speculative_model` values through `llm_models_root()` while preserving absolute paths. This keeps the YAML portable across CI/local model roots.

Also makes the GSM8K lm-eval parser tolerate padded table cells, matching the output shape emitted by the local-completions run.

Test entries:
- `test_disaggregated_qwen3_32b_fp8` smoke test in `l0_dgx_h200.yml`
- `test_disaggregated_stress_test::qwen3_32b_fp8_stress` in `qa/llm_function_stress.txt`, `request_count=10000`, `accuracy_threshold=0.42`

Refs: TRTLLM-12154

## Test plan

- [x] Targeted smoke test passed before the upstream rebase with FP8 KV + Eagle3
- [x] Rebuild on upstream main after rebase
- [x] Rerun `tests/integration/defs/disaggregated/test_disaggregated.py::test_disaggregated_qwen3_32b_fp8` after rebuild
- [x] Locally validated the stress node with temporary request/output/lm-eval limits; aiperf completed 16/16 requests and GSM8K parsed as 0.75 against the 0.42 threshold. Temporary limits are not committed.
- [x] Pre-merge CI

## Release Notes

* **Tests**
  * Added disaggregated test coverage for Qwen3-32B-FP8 model with speculative decoding configuration.
  * Improved GSM8K accuracy extraction to support variable whitespace and both integer and decimal values.
  * Extended stress test parametrization to include new Qwen3-32B-FP8 test scenarios on H200 GPUs.

[Review Change Stack](https://app.coderabbit.ai/change-stack/NVIDIA/TensorRT-LLM/pull/14278?utm_source=github_walkthrough&utm_medium=github&utm_campaign=change_stack)

### CODE REVIEW

**Comment by brnguyen2** [comment]
/bot run --extra-stage "DGX_H200-8_GPUs-PyTorch-Post-Merge-1"

**Comment by brnguyen2** [comment]
/bot run --extra-stage "DGX_H200-8_GPUs-PyTorch-Post-Merge-1"

**Comment by brnguyen2** [comment]
/bot run --extra-stage "DGX_H200-8_GPUs-PyTorch-Post-Merge-1"

**Comment by brnguyen2** [comment]
/bot run --disable-fail-fast --stage-list "DGX_H200-8_GPUs-PyTorch-Post-Merge-1"

**Comment by brnguyen2** [comment]
/bot run --disable-fail-fast --stage-list "DGX_H200-8_GPUs-PyTorch-Post-Merge-1"

**Comment by brnguyen2** [comment]
Verified that the targeted rerun reached the newly added test and it passed:

`DGX_H200-8_GPUs-PyTorch-Post-Merge-1/disaggregated/test_disaggregated.py::test_disaggregated_qwen3_32b_fp8[Qwen3/Qwen3-32B-FP8]`

The selected test run completed successfully with this pytest summary: `16 passed, 12 skipped, 17175 deselected`.

**Comment by brnguyen2** [comment]
Hi @NVIDIA/trt-llm-qa-serving and @NVIDIA/trt-llm-qa, this PR is ready for review.

I addressed the naming nit, and a fresh pipeline is running after the trivial naming-only follow-up/rebase. The previous targeted H200 validation selected and passed the new disagg test; I do not expect the latest naming-only change to affect runtime behavior.

Could someone please take a look when available?

**Review by tburt-nv — APPROVED** [review]

File: tests/integration/defs/disaggregated/test_disaggregated.py [hunk 1]
```diff
@@ -292,6 +294,13 @@ def setup_model_symlink(llm_venv, model_root, dest_subpath):
         os.symlink(model_root, dst, target_is_directory=True)
 
 
+def _resolve_llm_model_path(model_path: str) -> str:
+    """Resolve a model subpath relative to the test LLM model root."""
+    if os.path.isabs(model_path):
+        return model_path
+    return os.path.join(llm_models_root(), model_path)
```
Comment (pcastonguay) [inline tests/integration/defs/disaggregated/test_disaggregated.py]: This could probably be moved to `common.py` as it's not specific to disaggregated tests.

**Review by pcastonguay — APPROVED** [review]
One small nit, otherwise lgtm.

File: tests/integration/defs/disaggregated/test_disaggregated.py (hunk 1 above)
Comment (brnguyen2) [reply tests/integration/defs/disaggregated/test_disaggregated.py]: Done. Moved the helper into `tests/integration/defs/common.py` and updated the disaggregated test to import it from there. I also validated the targeted Qwen3 FP8 disaggregated test before pushing.

**Comment by brnguyen2** [comment]
The recent CI failure on this PR (`L0_MergeRequest_PR #39365` → `L0_Test-x86_64-Single-GPU #2493`, stage `[DGX_B200-PyTorch-5]`) is an unrelated pre-existing regression on `main`:

- Failing test: `accuracy/test_llm_api_pytorch.py::TestQwen3_5_35B_A3B::test_bf16_mtp[mtp_on]`
- Error: `AttributeError: 'NoneType' object has no attribute 'gather_ids'` at `tensorrt_llm/_torch/models/modeling_speculative.py:1748` during autotuner warmup.
- Likely introduced by #14164 (Qwen3.5 VL MoE) — Qwen3.5-35B-A3B text MoE is being routed through `modeling_qwen3vl.py` and `spec_metadata` is `None` during the warmup forward.
- The `mtp_off` variant of the same test passes.
- Tracked in https://nvbugs/6206179.

This PR only touches the Qwen3-32B FP8 disagg stress test plumbing — none of its files are related to `modeling_speculative.py` / `modeling_qwen3vl.py` / autotuner warmup. No upstream commit since `96a4a0937e` touches those files, so a rebase doesn't help. The latest commit on this branch (473ba2c4cb) waives the failing test pending an upstream fix.

Failure analysis: https://pbss.s8k.io/v1/AUTH_svc_tensorrt/sw-tensorrt-ci-analysis/LLM/main/L0_MergeRequest_PR/39365/failure_analysis.html

**Comment by tburt-nv** [comment]
/bot skip --comment "DGX_B200-8_GPUs-PyTorch-2 and RTXPro6000D-PyTorch-1 passed in 42359"
