### PR TITLE
[None][fix] AutoDeploy: Fix unit tests due to missing attribute in DemoLLM

### PR DESCRIPTION
**Pull request by galagam**
## Description

AutoDeploy unit tests relying on DemoLLM are failing with:
```AttributeError: 'DemoLLM' object has no attribute '_post_processor_hook'```
New regression entered in PR https://github.com/NVIDIA/TensorRT-LLM/pull/15239
Minimal fix: Define `_post_processor_hook` in `DemoLLM`.

## PR Checklist

Please review the following before submitting your PR:
- PR description clearly explains what and why. If using CodeRabbit's summary, please make sure it makes sense.
- PR Follows [TRT-LLM CODING GUIDELINES](https://github.com/NVIDIA/TensorRT-LLM/blob/main/CODING_GUIDELINES.md) to the best of your knowledge.
- Test cases are provided for new code paths (see [test instructions](https://github.com/NVIDIA/TensorRT-LLM/tree/main/tests#1-how-does-the-ci-work))
- If PR introduces API changes, an appropriate PR label is added - either `api-compatible` or `api-breaking`. For `api-breaking`, include `BREAKING` in the PR title.
- Any new dependencies have been scanned for license and vulnerabilities
- [CODEOWNERS](https://github.com/NVIDIA/TensorRT-LLM/blob/main/.github/CODEOWNERS) updated if ownership changes
- Documentation updated as needed
- Update [tava architecture diagram](https://github.com/NVIDIA/TensorRT-LLM/blob/main/.github/tava_architecture_diagram.md) if there is a significant design change in PR.
- The reviewers assigned automatically/manually are appropriate for the PR.

- [x] Please check this after reviewing the above items as appropriate for this PR.

## GitHub Bot Help

To see a list of available CI bot commands, please comment `/bot help`.

### CODE REVIEW

**Review by nvchenghaoz — APPROVED** [review]

**Comment by tburt-nv** [comment]
I think we can close this due to https://github.com/NVIDIA/TensorRT-LLM/pull/15629

**Comment by galagam** [comment]
Closing since culprit commit was reverted https://github.com/NVIDIA/TensorRT-LLM/pull/15629
@xwang233 please take this patch if you plan to re-integrate https://github.com/NVIDIA/TensorRT-LLM/pull/15239
