### PR TITLE
[https://nvbugs/6480574][fix] mpi_session: guard MpiPoolSession.shutdown against partial init

### PR DESCRIPTION
**Pull request by lowsfer**
## Summary

`MpiPoolSession.shutdown()` reads `self.n_workers` (in a log line) and `self._wait_shutdown` **unguarded**, but it is reachable on a session that never completed `__init__`:

- from `__del__` → `shutdown_abort()` → `shutdown()` on a partially-constructed object, and
- from the released-session path, e.g. `tests/unittest/executor/test_proxy_fast_death.py::test_pool_session_shutdown_never_blocks_after_release`, which builds the object with `MpiPoolSession.__new__(MpiPoolSession)`.

In those states the attributes are absent and `shutdown()` raises `AttributeError: 'MpiPoolSession' object has no attribute 'n_workers'` (then `... '_wait_shutdown'`). The `_pool_dead` check immediately above already uses `getattr(self, '_pool_dead', False)` defensively for exactly this reason.

## Fix

Guard both accesses with `getattr(...)`, matching the existing `_pool_dead` style, so a released or partially-constructed session shuts down cleanly instead of raising.

## Why main is currently red

This is a **cross-PR merge skew**, each half green on its own:

- the unguarded `self.n_workers` log line was added by #16456 (2026-07-16), and
- the `__new__`-based test that trips it was added by #16312 (2026-07-20).

Neither failed in isolation; the combination on `main` fails **deterministically**. `main` has been red on `test_pool_session_shutdown_never_blocks_after_release` since #16312 landed, and the fix is a small robustness guard.

## Test

`test_proxy_fast_death.py` now passes in full (**23 passed**, was 1 failed):

```
python -m pytest tests/unittest/executor/test_proxy_fast_death.py -q
# 23 passed
```

(No behavior change for fully-initialized sessions: `n_workers` / `_wait_shutdown` are always set by `__init__`; the guards only affect objects that bypass it.)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

* **Documentation**
  * Improved formatting and organization of API documentation.
  * Clarified session initialization and external communication examples.

* **Bug Fixes**
  * Improved shutdown logging when the worker count is unavailable.
  * Preserved existing worker cleanup and shutdown behavior.

### CODE REVIEW

**Comment by lowsfer** [comment]
Rebased onto latest main and **removed the temporary waiver** for `test_proxy_fast_death.py::test_pool_session_shutdown_never_blocks_after_release` (nvbugs/6480574, added by the auto-waive PR #16615) so CI now re-validates the previously-failing test.

This PR is the fix for **nvbugs/6480574 / TRTLLM-14480**. Empirical confirmation of the fix from recent CI on the same test:
- Build `L0_MergeRequest_PR #48602` (unguarded `shutdown()`) → `AttributeError: 'MpiPoolSession' object has no attribute 'n_workers'`
- The next commit adding the `getattr` guard passed with the same test present (builds `#48694` / `#48718`)

The failure is a cross-PR merge skew (unguarded `n_workers` log line from #16456 + the `__new__`-based test from #16312); deterministic on main, hence the auto-waive.

**Comment by lowsfer** [comment]
Closing in favor of #16630 by @JunyiXu-nv (the nvbugs/6480574 assignee), which fixes the same failure test-side by seeding the `__new__`-bypassed attributes in `test_pool_session_shutdown_never_blocks_after_release`.

For the record, empirical CI confirmation of the root cause (same test): build `L0_MergeRequest_PR #48602` (unguarded) failed with `AttributeError: 'MpiPoolSession' object has no attribute 'n_workers'`; the next commit adding the guard passed (`#48694`/`#48718`). Thanks @JunyiXu-nv for taking it.
