### ISSUE TITLE
quantize.py does not recognize model_dir param with version > 0.16.0

### ISSUE THREAD

**Issue by liangjason87** [NVIDIA/TensorRT-LLM#3349]
### System Info

Seems like post 0.16.0, quantize.py seems to recognize model_dir as a param when attempting to quantize model weights (models attempted were 3.1 8b and 3.1 70b). The following error is thrown:

[TensorRT-LLM] TensorRT-LLM version: 0.17.0.post1
Traceback (most recent call last):
  File "/opt/TensorRT-LLM-examples/quantization/quantize.py", line 157, in <module>
    quantize_and_export(
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/quantization/quantize_by_modelopt.py", line 629, in quantize_and_export
    model = get_model(model_dir, dtype, device=device, device_map=device_map)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tensorrt_llm/quantization/quantize_by_modelopt.py", line 281, in get_model
    model = model_cls.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/auto/auto_factory.py", line 573, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/modelopt/torch/opt/plugins/huggingface.py", line 84, in _new_from_pretrained
    model = types.MethodType(cls._modelopt_cache["from_pretrained"].__func__, cls)(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/modeling_utils.py", line 272, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/modeling_utils.py", line 4455, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _new__load_pretrained_model() missing 1 required positional argument: 'pretrained_model_name_or_path'

Run with this command (worked in 0.16.0):

python /opt/TensorRT-LLM-examples/quantization/quantize.py --model_dir /msft/Llama-3.1-8B-Instruct --dtype bfloat16 --qformat fp8 --kv_cache_dtype fp8 --output_dir /msft/llama/llg_trtllm_checkpoints_llama3_1_8B_HF_bf16_fp8_tp1_pp1_2gpu_251803 --calib_size 512 --tp_size 1 --pp_size 1

Unsure if the behavior of this param has changed or a different value is expected? Thank you!

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Attempt to run quantize.py with this command:

python /opt/TensorRT-LLM-examples/quantization/quantize.py --model_dir /msft/Llama-3.1-8B-Instruct --dtype bfloat16 --qformat fp8 --kv_cache_dtype fp8 --output_dir /msft/llama/llg_trtllm_checkpoints_llama3_1_8B_HF_bf16_fp8_tp1_pp1_2gpu_251803 --calib_size 512 --tp_size 1 --pp_size 1

### Expected behavior

Accepts path to local model weights.

### actual behavior

Does not recognize the path and expects a HF link.

### additional notes

Observed in versions after 0.16.0

**Comment by mayani-nv** [comment]
I was trying to repro this but it works fine for me
```
python3 ../quantization/quantize.py --model_dir /mnt/mayani/Meta-Llama-3.1-8B-Instruct/ --dtype float16 --qformat fp8 --kv_cache_dtype fp8 --output_dir /mnt/mayani/tllm_chkpt_1gpu_fp8 --calib_size 512 --tp_size 1
2025-04-07 18:11:31,825 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend
[TensorRT-LLM] TensorRT-LLM version: 0.19.0.dev2025040100
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:06<00:00,  1.67s/it]
README.md: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15.6k/15.6k [00:00<00:00, 155MB/s]
train-00000-of-00003.parquet: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 257M/257M [00:00<00:00, 269MB/s]
train-00001-of-00003.parquet: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 257M/257M [00:00<00:00, 289MB/s]
train-00002-of-00003.parquet: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 259M/259M [00:00<00:00, 289MB/s]
validation-00000-of-00001.parquet: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 34.7M/34.7M [00:00<00:00, 287MB/s]
test-00000-of-00001.parquet: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30.0M/30.0M [00:00<00:00, 290MB/s]
Generating train split: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 287113/287113 [00:02<00:00, 112117.19 examples/s]
Generating validation split: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13368/13368 [00:00<00:00, 115711.15 examples/s]
Generating test split: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11490/11490 [00:00<00:00, 116754.01 examples/s]
Inserted 675 quantizers
/usr/local/lib/python3.12/dist-packages/modelopt/torch/export/postprocess.py:750: UserWarning: Enable lm_head quantization. lm_head quantization may lead to additional accuracy loss.
  warn(
current rank: 0, tp rank: 0, pp rank: 0
```
The steps i used are following
```
# download the HF checkpoint
git clone git@hf.co:meta-llama/Meta-Llama-3.1-8B-Instruct
Cloning into 'Meta-Llama-3.1-8B-Instruct'...

# install the trtllm 
pip install tensorrt-llm==0.19.0.dev2025040100
cd TensorRT-LLM
git submodule update --init --recursive
git lfs pull
```

**Comment by liangjason87** [comment]
Hi @mayani-nv, thanks for your response! Did the same steps but still hitting this issue. Noticed you were on a dev version of 0.19 trtllm, could you try a non-dev release of 0.18.0 (or any version lower but greater than 0.16.0)? Appreciate it.

**Comment by mayani-nv** [comment]
I tried with the `0.18.0` branch of TensorRT-LLM github and did  pip version as well. The following is my steps
```
#clone repo
cd TensorRT-LLM && git checkout v0.18.0
git submodule update --init --recursive
git lfs pull

# pip install in fresh virtual environment
python3 -m venv trt_env
source trt_env/bin/activate
pip install tensorrt-llm==0.18.0 --extra-index-url https://pypi.nvidia.com

# download the HF ckpt
git clone https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct
git lfs pull # you might need to do this as well

# use the quantization script
cd TensorRT/examples/llama

# run quantization
python3 ../quantization/quantize.py --model_dir /workspace/Meta-Llama-3.1-8B-Instruct/ --dtype float16 --qformat fp8 --kv_cache_dtype fp8 --output_dir /mnt/mayani/tllm_chkpt_1gpu_fp8 --calib_size 512 --tp_size 1
2025-04-10 05:11:11,282 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend
[TensorRT-LLM] TensorRT-LLM version: 0.18.0
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.51it/s]
README.md: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15.6k/15.6k [00:00<00:00, 97.6MB/s]
train-00000-of-00003.parquet: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 257M/257M [00:05<00:00, 42.8MB/s]
train-00001-of-00003.parquet: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 257M/257M [00:06<00:00, 40.2MB/s]
train-00002-of-00003.parquet: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 259M/259M [00:05<00:00, 46.2MB/s]
validation-00000-of-00001.parquet: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 34.7M/34.7M [00:00<00:00, 51.8MB/s]
test-00000-of-00001.parquet: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30.0M/30.0M [00:00<00:00, 55.6MB/s]
Generating train split: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 287113/287113 [00:02<00:00, 129155.91 examples/s]
Generating validation split: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13368/13368 [00:00<00:00, 130750.76 examples/s]
Generating test split: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11490/11490 [00:00<00:00, 125176.11 examples/s]
Inserted 675 quantizers
/workspace/TensorRT-LLM/examples/llama/trt_env/lib/python3.12/site-packages/modelopt/torch/export/postprocess.py:750: UserWarning: Enable lm_head quantization. lm_head quantization may lead to additional accuracy loss.
  warn(
current rank: 0, tp rank: 0, pp rank: 0
```

**Comment by kota-iizuka** [comment]
I tried quantizing the Llama 3.2 1B model with the following command, and got a similar error with tensorrt-llm=0.18.1, transformers==4.51.1, 4.50.0. It worked with transformers==4.48.3, 4.49.0, so I guess a change occurred between 4.49.0 and 4.50.0.

```
python TensorRT-LLM/examples/quantization/quantize.py --model_dir $HF_MODEL_DIR --qformat int4_awq --awq_block_size 128 --output_dir ./tllm_llama32_1b_1gpu_tp1_int4
```

**Comment by kota-iizuka** [comment]
The `loaded_state_dict_keys` variable specification has disappeared from https://github.com/huggingface/transformers/blob/a22a4378d97d06b7a1d9abad6e0086d30fdea199/src/transformers/modeling_utils.py#L4322 to https://github.com/huggingface/transformers/blob/0b057e66b52556da3a1cbc29e2a98c0784ea9c33/src/transformers/modeling_utils.py#L4458

**Comment by kota-iizuka** [comment]
Running `pip install nvidia-modelopt==0.27.0` fixed it https://github.com/NVIDIA/TensorRT-Model-Optimizer/issues/169

**Comment by karljang** [comment]
@liangjason87 , 
For quantization, we recommend using the TensorRT Model Optimizer. You can try it with the following command:
```
python TensorRT-Model-Optimizer/examples/llm_ptq/hf_ptq.py --pyt_ckpt_path=Llama-3.1-8B-Instruct --export_path=model_quantized --qformat=fp8 --export_fmt=hf --kv_cache_qformat=fp8 --calib_size=512 --trust_remote_code
```
